# Generated by Django 5.0.6 on 2024-05-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_service_reservation_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='services',
            new_name='service',
        ),
    ]
