# Generated by Django 5.0.6 on 2024-05-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_services_reservation_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='service',
            new_name='services',
        ),
    ]
